version: "3"
services:
  web:
    image: node:19-alpine
    working_dir: /app
    volumes:
      - ./web:/app
      - ./node_modules:/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    restart: unless-stopped
    tty: true

  server:
    image: node:19-alpine
    working_dir: /app
    volumes:
      - ./server:/app
      - ./node_modules:/node_modules
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres/gamenight
    command: npm run start
    restart: unless-stopped
    tty: true

  postgres:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamenight

volumes:
  db-data:
