/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as PublicLoginRouteImport } from './routes/_public/login/route'
import { Route as PublicLandingRouteImport } from './routes/_public/_landing/route'
import { Route as AuthEventsRouteImport } from './routes/_auth/events/route'

// Create Virtual Routes

const PublicLandingIndexLazyImport = createFileRoute('/_public/_landing/')()

// Create/Update Routes

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const PublicLoginRouteRoute = PublicLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PublicLandingRouteRoute = PublicLandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => PublicRouteRoute,
} as any)

const AuthEventsRouteRoute = AuthEventsRouteImport.update({
  path: '/events',
  getParentRoute: () => AuthRouteRoute,
} as any)

const PublicLandingIndexLazyRoute = PublicLandingIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PublicLandingRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/_landing/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth/events': {
      preLoaderRoute: typeof AuthEventsRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_public/_landing': {
      preLoaderRoute: typeof PublicLandingRouteImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/login': {
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteImport
    }
    '/_public/_landing/': {
      preLoaderRoute: typeof PublicLandingIndexLazyImport
      parentRoute: typeof PublicLandingRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRouteRoute.addChildren([AuthEventsRouteRoute]),
  PublicRouteRoute.addChildren([
    PublicLandingRouteRoute.addChildren([PublicLandingIndexLazyRoute]),
    PublicLoginRouteRoute,
  ]),
])

/* prettier-ignore-end */
